version: 0.0
os: linux

# 배포 파일 설정
files:
  - source: / # 인스턴스에 복사할 디렉터리 경로
    destination: /home/ubuntu/Yakchat_Server_Test # 인스턴스에서 파일이 복사되는 위치
    overwrite: yes #복사할 위치에 파일이 있는 경우 대체

# files 섹션에서 복사한 파일에 대한 권한 설정
permissions:
  - object: / # 권한이 지정되는 파일 또는 디렉터리
    pattern: "**" # 매칭되는 패턴에만 권한 부여(optional)
    owner: ec2-user # object 의 소유자(optional)
    group: ec2-user # object 의 그룹 이름(optional)

# 배포 이후에 실행할 일련의 라이프사이클
hooks:
  ApplicationStart: # 종료 및 새로운 애플리케이션을 실행
    - location: scripts/deploy.sh # hooks 에서 실행할 스크립트 위치
      timeout: 300 # 스크립트 실행에 허용되는 최대 시간이며, 넘으면 배포 실패로 간주됨(optional)
      runas: ec2-user # 스크립트를 실행하는 사용자(optional)